#pragma once
#include <stdint.h>

// The terraPen logo's single stroke as a polyline, in drawing order -- the
// path the source animation's pen dot travels. GENERATED by
// tools/gen_logo.py alongside icon_logo; rerun that rather than editing.
//
// Coordinates are on the 240px design grid (ui_scale.h), in 1/8 px units,
// relative to the top-left of the same 128x128 box iconLogo fills there.

struct LogoStrokePoint
{
    int16_t x, y;
};

static const int LOGO_STROKE_SUBPX = 8;
static const int LOGO_STROKE_BOX = 128; // px on the 240 grid
extern const LogoStrokePoint LOGO_STROKE[];
extern const int LOGO_STROKE_COUNT;
