#pragma once
#include <lvgl.h>

// Lucide icons (lucide.dev) as LVGL font glyphs. Lucide is ISC-licensed, with
// some icons derived from Feather (MIT); notices in fonts/LICENSE-lucide.txt.
// GENERATED by tools/gen_lucide_font.py from lucide-static 1.48.0 -- edit
// the ICONS list there and rerun rather than editing this file.
//
// lucide_<size> draws these icons and falls back to lv_font_montserrat_<size>
// for everything else, so it replaces the Montserrat font of the same size
// on any label that shows an icon -- including mixed strings such as
// LUCIDE_PLAY " Run". The icons only render in a lucide_* font.

LV_FONT_DECLARE(lucide_12)
LV_FONT_DECLARE(lucide_14)
LV_FONT_DECLARE(lucide_16)
LV_FONT_DECLARE(lucide_18)
LV_FONT_DECLARE(lucide_24)
LV_FONT_DECLARE(lucide_32)

#define LUCIDE_HOUSE              "\xEE\x83\xB5" // house
#define LUCIDE_MOVE               "\xEE\x84\xA1" // move
#define LUCIDE_PEN                "\xEE\x84\xAF" // pen
#define LUCIDE_PEN_LINE           "\xEE\x84\xB0" // pen-line
#define LUCIDE_CARD_SIM           "\xEE\x99\xB1" // card-sim
#define LUCIDE_FOLDER             "\xEE\x83\x97" // folder
#define LUCIDE_FOLDER_OPEN        "\xEE\x89\x87" // folder-open
#define LUCIDE_FILE               "\xEE\x83\x80" // file
#define LUCIDE_CAMERA             "\xEE\x81\xA4" // camera
#define LUCIDE_LIGHTBULB          "\xEE\x87\x82" // lightbulb
#define LUCIDE_SETTINGS           "\xEE\x85\x94" // settings
#define LUCIDE_CIRCLE_STOP        "\xEE\x82\x83" // circle-stop
#define LUCIDE_OCTAGON_X          "\xEE\x84\xA8" // octagon-x
#define LUCIDE_SQUARE             "\xEE\x85\xA7" // square
#define LUCIDE_PAUSE              "\xEE\x84\xAE" // pause
#define LUCIDE_PLAY               "\xEE\x84\xBC" // play
#define LUCIDE_WIFI               "\xEE\x86\xAE" // wifi
#define LUCIDE_WIFI_COG           "\xEE\x99\xB4" // wifi-cog
#define LUCIDE_MONITOR            "\xEE\x84\x9D" // monitor
#define LUCIDE_INFO               "\xEE\x83\xB9" // info
#define LUCIDE_SLIDERS_HORIZONTAL "\xEE\x8A\x9A" // sliders-horizontal
#define LUCIDE_WRENCH             "\xEE\x86\xB1" // wrench
#define LUCIDE_CPU                "\xEE\x82\xA9" // cpu
#define LUCIDE_COG                "\xEE\x8C\x8B" // cog
#define LUCIDE_PENCIL_RULER       "\xEE\x93\xB1" // pencil-ruler
#define LUCIDE_DRAFTING_COMPASS   "\xEE\x94\xA7" // drafting-compass
#define LUCIDE_PRINTER            "\xEE\x85\x81" // printer
#define LUCIDE_ROUTER             "\xEE\x8E\xBF" // router
#define LUCIDE_EYE                "\xEE\x82\xBA" // eye
#define LUCIDE_EYE_OFF            "\xEE\x82\xBB" // eye-off
#define LUCIDE_X                  "\xEE\x86\xB2" // x
#define LUCIDE_CHECK              "\xEE\x81\xAC" // check
#define LUCIDE_DELETE             "\xEE\x82\xAE" // delete
#define LUCIDE_CHEVRON_LEFT       "\xEE\x81\xAE" // chevron-left
#define LUCIDE_CHEVRON_RIGHT      "\xEE\x81\xAF" // chevron-right
#define LUCIDE_ARROW_LEFT         "\xEE\x81\x88" // arrow-left
#define LUCIDE_REFRESH_CW         "\xEE\x85\x85" // refresh-cw
#define LUCIDE_TRIANGLE_ALERT     "\xEE\x86\x93" // triangle-alert
#define LUCIDE_TRASH_2            "\xEE\x86\x8E" // trash-2
#define LUCIDE_ARROW_UP_DOWN      "\xEE\x8D\xBD" // arrow-up-down
#define LUCIDE_ROTATE_CCW         "\xEE\x85\x88" // rotate-ccw
